services:
  - type: web
    name: in-between-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "https://in-between.live,https://amatasek.github.io"
      - key: DATA_PATH
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 4
