name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: 'web/package-lock.json'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd web
          npm install
      
      - name: Build web app
        run: |
          cd web
          # Create next.config.js file for static export
          echo 'module.exports = { output: "export" };' > next.config.js
          # Create .env.production file with environment variables
          echo 'NEXT_PUBLIC_API_URL=https://in-between-api.onrender.com' > .env.production
          echo 'NEXT_PUBLIC_SOCKET_URL=https://in-between-api.onrender.com' >> .env.production
          # Build the app
          npm run build
          # Ensure the out directory exists
          mkdir -p out
      
      # Create a CNAME file for the custom domain
      - name: Create CNAME file
        run: echo "in-between.live" > web/out/CNAME
      
      # Copy index.html to 404.html for SPA routing
      - name: Create 404 page
        run: cp web/out/index.html web/out/404.html
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/out
          branch: gh-pages
          clean: true
