name: Deploy Backend to Azure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd server
          npm ci
      
      - name: Create database directory
        run: |
          mkdir -p db
          touch db/.gitkeep
      
      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./server
      
      - name: Configure Azure App Service settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set --name ${{ vars.AZURE_WEBAPP_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --settings \
              NODE_ENV=production \
              PORT=8080 \
              JWT_SECRET=${{ secrets.JWT_SECRET }} \
              CORS_ORIGIN=${{ vars.CORS_ORIGIN }} \
              DB_PATH=/home/site/wwwroot/db
