name: Deploy Frontend to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd web
          npm ci
      
      - name: Build web app
        run: |
          cd web
          npm run export
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL || 'https://api.in-between.live' }}
          REACT_APP_SOCKET_URL: ${{ vars.REACT_APP_SOCKET_URL || 'https://api.in-between.live' }}
      
      # Create a CNAME file for the custom domain
      - name: Create CNAME file
        run: echo "in-between.live" > web/out/CNAME
      
      # Copy index.html to 404.html for SPA routing
      - name: Create 404 page
        run: cp web/out/index.html web/out/404.html
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/out
          branch: gh-pages
          clean: true
